---
title: "Inferência Bayesiana"
subtitle: "Disciplina CE227 da graduação em Estatística UFPR"
output: html_document
---

Página dedicada ao armazenamento e disponibilização dos materiais
elaborados na disciplina
[CE227 - Inferência Bayesiana][ce227],
ofertada pelo departamento de Estatística na Universidade Federal do
Paraná como disciplina optativa, ministrada pelo professor
[Paulo Justiniano][pj].

Na disciplina seguimos, inicialmente, as notas de aula elaborados pelo
professor Stuart Coles, cuja tradução, adpatação e extensão esta sendo
feita pelo professor da disciplina,
[Apostila de Inferência Bayesiana][apostila]. Outras referências são
listadas na [página da disciplina][ce227]. Após discutidos os tópicos da
apostila, aplicações de inferência bayesiana em problemas reais foram
apresentados e discutidos.

A condução dos encontrou se deu de forma bastante dinâmica e a cada novo
conteúdo atividades eram propostas. Neste repositório armazena-se
algumas dessas atividades. Os arquivos elaborados durante a disciplina
estão disponíveis nos links abaixo:

 * [Exemplo intenção de voto](./01-intecaovoto.html)
 * [Princípio da Verossimilhança](./02-pvalor.html)
 * [Inferência sobre o parâmetro de forma da Gamma](./03-gamma-jeffrey.pdf)
 * [FBST - Full Bayesian Significance Test](./04-fbst.html)
 * [Exemplo teórico (da avaliação)](./05-prova.html)
 * [Exemplos prático (análise de experimento)](./06-namatodes.html)

<!--------------------------------------------- -->
[ce227]: http://www.leg.ufpr.br/doku.php/disciplinas:ce227-2016-01
[pj]: http://www.leg.ufpr.br/~paulojus/
[apostila]: http://www.leg.ufpr.br/lib/exe/fetch.php/disciplinas:ce227:inferenciabayesiana.pdf
[GNU General Public License, versão 3]: https://www.gnu.org/licenses/gpl-3.0.html
[`LICENSE.md`]: https://github.com/JrEduardo/ce227-bayes/blob/master/LICENSE.md
